[main]
abi_df_file_path = "ABIs/ethereum__abis.parquet"
abi_folder_path = "ABIs/abi_database"
raw_logs_folder_path = "data/logs"

[abi_reader]
existing_df_joining_key = "id"

[decoder]
max_concurrent_files_decoding = 16
max_chunk_threads_per_file = 16
decoded_chunk_size = 500_000
